# Generated by Django 5.1.1 on 2024-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="account_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
