# Generated by Django 5.1.1 on 2024-10-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_customuser_is_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("customer", "Customer"),
                    ("employee", "Employee"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("customer", "Customer"),
                    ("employee", "Employee"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
