# Generated by Django 5.1.1 on 2024-10-07 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_account_updated_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
