# Generated by Django 5.1.1 on 2024-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default=None, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="phone_number",
            field=models.CharField(db_index=True, default=None, max_length=11),
            preserve_default=False,
        ),
    ]
