# Generated by Django 5.1.1 on 2024-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="phone_number",
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
    ]
