# Generated by Django 5.1.1 on 2024-10-18 10:51

import django.db.models.deletion
import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("ground_floor", "Ground Floor"),
                            ("bungalow", "Bungalow"),
                            ("ocean_view", "Ocean View Room"),
                            ("deluxe", "Deluxe"),
                            ("suite", "Suite"),
                            ("resort", "Resort"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        choices=[
                            ("2", "2 người"),
                            ("4", "4 người"),
                            ("6", "6 người"),
                            ("8", "8 người"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area", models.FloatField()),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=rooms.models.RoomType.upload_image_to,
                    ),
                ),
                (
                    "image_bathroom",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=rooms.models.RoomType.upload_image_to,
                    ),
                ),
                (
                    "image_amenities",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=rooms.models.RoomType.upload_image_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trống", "Trống"),
                            ("đã đặt", "Đã đặt"),
                            ("đang bảo trì", "Đang bảo trì"),
                        ],
                        default="trống",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="rooms.roomtype",
                    ),
                ),
            ],
        ),
    ]
