# Generated by Django 5.1.1 on 2024-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("ground_floor", "Ground Floor"),
                            ("bungalow", "Bungalow"),
                            ("ocean_view", "Ocean View Room"),
                            ("deluxe", "Deluxe"),
                            ("suite", "Suite"),
                            ("resort", "Resort"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        choices=[
                            ("2", "2 người"),
                            ("2-4", "2-4 người"),
                            ("4-6", "4-6 người"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trống", "Trống"),
                            ("đã đặt", "Đã đặt"),
                            ("đang bảo trì", "Đang bảo trì"),
                        ],
                        default="Trống",
                        max_length=20,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="room_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
