# Generated by Django 5.1.1 on 2024-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
