# Generated by Django 5.1.1 on 2024-09-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("family", "Family"),
                    ("ground_floor", "Ground Floor"),
                    ("bungalow", "Bungalow"),
                    ("ocean_view", "Ocean View Room"),
                    ("deluxe", "Deluxe"),
                    ("suite", "Suite"),
                    ("resort", "Resort"),
                ],
                max_length=20,
            ),
        ),
    ]
