# Generated by Django 5.1.1 on 2024-10-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_image_alter_room_name_roomimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
    ]
