# Generated by Django 5.1.1 on 2024-10-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="price_per_night",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
