# Generated by Django 5.1.1 on 2024-09-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.CharField(
                choices=[("2", "2 người"), ("2-4", "2-4 người"), ("4-6", "4-6 người")],
                max_length=20,
            ),
        ),
    ]
