# Generated by Django 5.1.1 on 2024-10-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_room_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomimage",
            old_name="image_url",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("trống", "Trống"),
                    ("đã đặt", "Đã đặt"),
                    ("đang bảo trì", "Đang bảo trì"),
                ],
                default="trống",
                max_length=20,
            ),
        ),
    ]
