# Generated by Django 5.1.1 on 2024-10-03 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_rename_image_url_roomimage_image_alter_room_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoomImage",
        ),
    ]
