# Generated by Django 5.1.1 on 2024-10-03 06:00

import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0005_delete_roomimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image_amenities",
            field=models.ImageField(
                blank=True, null=True, upload_to=rooms.models.Room.upload_image_to
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="image_bathroom",
            field=models.ImageField(
                blank=True, null=True, upload_to=rooms.models.Room.upload_image_to
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=rooms.models.Room.upload_image_to
            ),
        ),
    ]
