# Generated by Django 5.1.1 on 2024-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="identity_card_number",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
