# Generated by Django 5.1.1 on 2024-10-12 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
