# Generated by Django 5.1.1 on 2024-10-18 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/avatars/%Y/%m/%d",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "svg"]
                    )
                ],
            ),
        ),
    ]
