# Generated by Django 5.1.1 on 2024-10-19 00:23

import customers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_alter_customer_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=customers.models.avatar_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "svg"]
                    )
                ],
            ),
        ),
    ]
