# Generated by Django 5.1.1 on 2024-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                ("interaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("interaction_date", models.DateField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("chat", "Chat"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
