# Generated by Django 5.1.1 on 2024-09-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInteraction",
            fields=[
                ("interaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("interaction_date", models.DateField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("chat", "Chat"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interactions",
                        to="employees.employee",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
