# Generated by Django 5.1.1 on 2024-09-28 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("customers", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinteraction",
            name="created_by",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_interactions",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="customerinteraction",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="customers.customer",
            ),
        ),
    ]
