# Generated by Django 5.1.1 on 2024-09-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("table_name", models.CharField(max_length=50)),
                ("column_name", models.CharField(max_length=50)),
                ("record_id", models.IntegerField()),
                ("translated_text", models.TextField()),
            ],
        ),
    ]
