# Generated by Django 5.1.1 on 2024-09-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("đã đặt", "Đã đặt"),
                            ("đang ở", "Đang ở"),
                            ("đã hoàn thành", "Đã hoàn thành"),
                            ("đã hủy", "Đã hủy"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
