# Generated by Django 5.1.1 on 2024-10-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("refunded", "Refunded"),
                    ("amended", "Amended"),
                    ("failed", "Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
