# Generated by Django 5.1.1 on 2024-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_alter_booking_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="booking_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="discount",
        ),
        migrations.AddField(
            model_name="booking",
            name="additional_charges",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xác nhận"),
                    ("confirmed", "Đã xác nhận"),
                    ("checked_in", "Đang ở"),
                    ("checked_out", "Đã trả phòng"),
                    ("cancelled", "Đã hủy"),
                    ("no_show", "Không đến"),
                    ("awaiting_payment", "Đang chờ thanh toán"),
                    ("refunded", "Đã hoàn tiền"),
                    ("amended", "Đã sửa đổi"),
                    ("failed", "Thất bại"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
