# Generated by Django 5.1.1 on 2024-10-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0004_rename_booking_date_booking_created_at_and_more"),
        ("customers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xác nhận"),
                    ("confirmed", "Đã xác nhận"),
                    ("checked_in", "Đang ở"),
                    ("checked_out", "Đã trả phòng"),
                    ("cancelled", "Đã hủy"),
                    ("no_show", "Không đến"),
                    ("awaiting_payment", "Đang chờ thanh toán"),
                    ("successful", "Đã thanh toán"),
                    ("refunded", "Đã hoàn tiền"),
                    ("amended", "Đã sửa đổi"),
                    ("failed", "Thất bại"),
                ],
                default="awaiting_payment",
                max_length=20,
            ),
        ),
    ]
