# Generated by Django 5.1.1 on 2024-10-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_booking_guest_email_booking_guest_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="guest_name",
            new_name="guest_firstname",
        ),
        migrations.AddField(
            model_name="booking",
            name="guest_lastname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
