# Generated by Django 5.1.1 on 2024-10-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_rename_guest_name_booking_guest_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
