# Generated by Django 5.1.1 on 2024-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_booking_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="promotion_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="services_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="stay_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="surcharge_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
