# Generated by Django 5.1.1 on 2024-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_booking_promotion_price_booking_services_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="promotion_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="services_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="stay_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="surcharge_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
