# Generated by Django 5.1.1 on 2024-10-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0009_alter_booking_promotion_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ xác nhận"),
                    ("confirmed", "Đã xác nhận"),
                    ("checked_in", "Đang ở"),
                    ("checked_out", "Đã trả phòng"),
                    ("cancelled", "Đã hủy"),
                    ("no_show", "Không đến"),
                    ("awaiting_payment", "Đang chờ thanh toán"),
                    ("successful", "Đã thanh toán"),
                    ("refunded", "Đã hoàn tiền"),
                    ("amended", "Đã sửa đổi"),
                    ("failed", "Thất bại"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
